// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux not configured.',
        );
      default:
        throw UnsupportedError(
          'Unsupported platform.',
        );
    }
  }

  // ✅ WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjDMbI1001jm4RSsuAObp32PdSa9XA5tE',
    appId: '1:82612883237:web:397f17ac1bd583e65394cc',
    messagingSenderId: '82612883237',
    projectId: 'social-go-f3f8b',
    authDomain: 'social-go-f3f8b.firebaseapp.com',
    storageBucket: 'social-go-f3f8b.firebasestorage.app',
    measurementId: '', // optional (only if Analytics enabled)
  );

  // ✅ ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA613Dgn8z49zrF9KGJWW5zwkz4vRSFjzE',
    appId: '1:82612883237:android:760a38b1f49151935394cc',
    messagingSenderId: '82612883237',
    projectId: 'social-go-f3f8b',
    storageBucket: 'social-go-f3f8b.firebasestorage.app',
  );

  // ✅ iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19bYRV7XSh-aD4kM0kbT7r5f0YuomoBk',
    appId: '1:82612883237:ios:5b76c13fb2da19548fd78a',
    messagingSenderId: '82612883237',
    projectId: 'social-go-f3f8b',
    storageBucket: 'social-go-f3f8b.firebasestorage.app',
    iosBundleId: 'com.example.web300Socialgo',
  );

  // ✅ macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19bYRV7XSh-aD4kM0kbT7r5f0YuomoBk',
    appId: '1:826128532351:ios:5b76c13fb2da19548fd78a',
    messagingSenderId: '826128532351',
    projectId: 'social-go-f3f8b',
    storageBucket: 'social-go-f3f8b.firebasestorage.app',
    iosBundleId: 'com.example.web300Socialgo',
  );

  // ✅ WINDOWS
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPjLW244V4Jq2xMCzLrYOELyFw_jepq48',
    appId: '1:82612883237:web:69cf7ee149ef1e7d8fd78a',
    messagingSenderId: '82612883237',
    projectId: 'social-go-f3f8b',
    authDomain: 'social-go-f3f8b.firebaseapp.com',
    storageBucket: 'social-go-f3f8b.firebasestorage.app',
    measurementId: '',
  );
}