// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPjLW244V4Jq2xMCzLrYOELyFw_jepq48',
    appId: '1:748223532351:web:802af9c8a0b0c14a8fd78a',
    messagingSenderId: '748223532351',
    projectId: 'fir-project-practice-9ac0d',
    authDomain: 'fir-project-practice-9ac0d.firebaseapp.com',
    storageBucket: 'fir-project-practice-9ac0d.firebasestorage.app',
    measurementId: 'G-3Z3073EX36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA613Dgn8z49zrF9KGJWW5zwkz4vRSFjzE',
    appId: '1:748223532351:android:9ed6a4537b9b91468fd78a',
    messagingSenderId: '748223532351',
    projectId: 'fir-project-practice-9ac0d',
    storageBucket: 'fir-project-practice-9ac0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19bYRV7XSh-aD4kM0kbT7r5f0YuomoBk',
    appId: '1:748223532351:ios:5b76c13fb2da19548fd78a',
    messagingSenderId: '748223532351',
    projectId: 'fir-project-practice-9ac0d',
    storageBucket: 'fir-project-practice-9ac0d.firebasestorage.app',
    iosBundleId: 'com.example.web300Socialgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19bYRV7XSh-aD4kM0kbT7r5f0YuomoBk',
    appId: '1:748223532351:ios:5b76c13fb2da19548fd78a',
    messagingSenderId: '748223532351',
    projectId: 'fir-project-practice-9ac0d',
    storageBucket: 'fir-project-practice-9ac0d.firebasestorage.app',
    iosBundleId: 'com.example.web300Socialgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPjLW244V4Jq2xMCzLrYOELyFw_jepq48',
    appId: '1:748223532351:web:69cf7ee149ef1e7d8fd78a',
    messagingSenderId: '748223532351',
    projectId: 'fir-project-practice-9ac0d',
    authDomain: 'fir-project-practice-9ac0d.firebaseapp.com',
    storageBucket: 'fir-project-practice-9ac0d.firebasestorage.app',
    measurementId: 'G-P73WD6762E',
  );
}
